# JVM arguments for the Gradle daemon.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Use JDK 17
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-17.0.20.8-hotspot

# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# R class
android.nonTransitiveRClass=true